### PR TITLE
update sv_hooks.lua

### PR DESCRIPTION
**Pull request by craighulme**
follow if statement standard

### CODE REVIEW

**Review by Meow — COMMENTED** [review]
This was done because on_drop and on_use can actually return nil, in which case we want nothing to happen and for the default behavior to occur.

Just check out what happens after the if statements. The default behavior is to remove the item from player's inventory. With your code, this will never happen.

**Comment by craighulme** [comment]
my bad, why don't you just do this `return result`

**Comment by Meow** [comment]
Notice how the code you changed actually has some more, default code running after the checks. That's why we can't just return the result and must check explicitly.

**Comment by craighulme** [comment]
right my bad, stupid oversight sorry. Was confused to why you did it but all cleared up, cheers

**Comment by Meow** [comment]
No problem, I make mistakes too, there is more spaghetti that falls out of my pockets than I can keep track of myself :P

**Pull request closed without merging**
